name: CryptoTracker

options:
  bundleIdPrefix: njdevelopment.CryptoTracker

settings:
  CURRENT_PROJECT_VERSION: 1a # CFBundleVersion build number
  MARKETING_VERSION: 1.0 # CFBundleShortVersionString version number
  GENERATE_INFOPLIST_FILE: YES

targets:
  CryptoTracker:
    type: application
    platform: iOS
    deploymentTarget: "17.5"
    sources: [CryptoTracker]